name = "Blase"
version = "0.1.0"
testDriver = "BlaseTest"
defaultTargets = ["Blase"]

[[lean_lib]]
name = "Blase"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "nightly-testing-2025-08-11"

[[lean_lib]]
name = "BlaseTest"
