name = "Blase"
version = "0.1.0"
testDriver = "BlaseTest"
defaultTargets = ["Blase"]
moreLeanArgs = ["--tstack=400000"]
moreServerArgs = ["--tstack=400000"]

[[lean_lib]]
name = "Blase"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "nightly-testing-2025-10-26"

[[lean_lib]]
name = "BlaseTest"

[[require]]
name = "SexprPBV"
path = "../SexprPBV"
rev = "main"
